name : Django Test

on:
  push:
    branchs:
        - main
  pull:
    branchs:
        - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - user : actions/checkout@v2
        - name : Set up python 3.12
            user : actions/setup-python@v2
            with : 
                python-version: '3.12'
        - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
        - name: Lint with flake8
            run: |
              pip install flake8
              flake8
        - name: Coverage report
            run: |
              pip install coverage
              coverage run manage.py test
              coverage report
        - name: Django Testing
            run: |
              python3 manage.py test
